name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  release:
    types: [published]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.7
      uses: actions/setup-python@v3
      with:
        python-version: "3.7"
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install build
    - name: Build package
      run: |
        python -m build
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: Build
        path: dist/*
      
    - name: Zip package
      if: github.event_name == 'release'
      run: |
        cd dist
        zip -r server99-websockify-token-plugin-release.zip .
        mv server99-websockify-token-plugin-release.zip ../
    
    - name: Upload to release
      if: github.event_name == 'release'
      uses: svenstaro/upload-release-action@2.9.0
      with:
        repo_token: ${{ secrets.TOKEN }}
        file: server99-websockify-token-plugin-release.zip
        tag: ${{ github.ref }}
        file_glob: true
